# Generated by Django 4.0.3 on 2022-04-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='schools',
            new_name='school',
        ),
    ]
